"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar, Navbar } from "@/components"
import {
  ThirdwebProvider,
  metamaskWallet,
  coinbaseWallet,
  walletConnect,
} from "@thirdweb-dev/react";
import useThemeStore from "@/store/themeStore";
import { Providers } from "./providers";
import { ClerkProvider } from '@clerk/nextjs'
import { StateContextProvider } from "@/context"
import { Sepolia, Localhost } from "@thirdweb-dev/chains";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { themes, activeTheme, setTheme } = useThemeStore((state) => state);

  return (
    <ClerkProvider>
      <html lang="en" className={`${activeTheme} `}>
        <body className="bg-background">
          <Providers>
            <ThirdwebProvider activeChain={Localhost} supportedChains={[Sepolia]}
              supportedWallets={[
                metamaskWallet({
                  recommended: true,
                }),
                coinbaseWallet(),
                walletConnect(),
              ]}
              clientId={process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID}
            >
              <StateContextProvider>

                <div className="relative sm:-8 p-4 min-h-screen flex flex-row">
                  <div className="sm:flex hidden mr-10 relative">
                    <Sidebar />
                  </div>
                  <div className="flex-1 max-sm:w-full max-w-[1280px] mx-auto sm:pr-5">
                    <Navbar />
                    {children}
                  </div>
                </div>
              </StateContextProvider>

            </ThirdwebProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
